language: php

php:
  - 5.3
  - 5.4

before_script:
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - php composer.phar require "symfony/http-foundation":"~2.1"

script:
  - php vendor/phpunit/phpunit/phpunit.php -c phpunit.xml.dist
