language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - php composer.phar require --dev "symfony/http-foundation":"*" "phpunit/phpunit":"*" "php-ffmpeg/php-ffmpeg":"*" "goodby/csv":"*"
  

script:
  - php vendor/phpunit/phpunit/phpunit.php -c phpunit.xml.dist
